# -- WINDOW SETTINGS --
WIDTH = 640
HEIGHT = 480
FPS = 60
CAPTION = "Asteroid City: Robot Saves the Day"

# -- COLOR TUPLES (RGB) --
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)

# -- ROBOT PLAYER SETTINGS --
PLAYER_SPEED = 4
PLAYER_BOTTOM_SCREEN_PADDING = 10

# -- GAMEPLAY DYNAMICS --
SPAWN_RATE = 150
INITIAL_ROCK_SPEED = 2
SPEED_INCREMENT = 0.5
LEVEL_UP_STEP = 10

# -- SCOREBOARD SETTINGS --
SCOREBOARD_X_PADDING = 20
SCOREBOARD_Y_OFFSET = 10

# -- FONT SETTINGS --
FONT_NAME = "Arial"
FONT_SIZE = 24

# -- GAME OVER SETTINGS --
GAME_OVER_WAIT = 3000 #milliseconds